
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS account_type text NOT NULL DEFAULT 'enterprise',
  ADD COLUMN IF NOT EXISTS full_name text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS country text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS city text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS sector text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS employee_count text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS website text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS profession text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS experience_years text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS skills text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS availability text NOT NULL DEFAULT '';
